AllLevels.set(1, {
    lvlHeight: 11,
    lvlWidth: 11,
    WallMap: [
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,],
        [1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,],
        [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,],
        [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,],
        [1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,],
        [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,],
        [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,]
    ],
    PacManStartingCoordinates: { row: 1, col: 5 },
    GhostToSpawnList: [
        { row: 5, col: 5, pathfindingStrategy: new AStarPathfindingStrategy(), speedratio: 0.9 },
        { row: 6, col: 5, pathfindingStrategy: new AStarPathfindingStrategy(), speedratio: 0.9 },
    ],
    CollictablesToSpawnList: [
        { type: "beer", col: 5, row: 9, },
        { type: "coin", col: 1, row: 1, },
        { type: "coin", col: 2, row: 1, },
        { type: "coin", col: 3, row: 1, },
        { type: "coin", col: 4, row: 1, },
        { type: "coin", col: 6, row: 1, },
        { type: "coin", col: 7, row: 1, },
        { type: "coin", col: 8, row: 1, },
        { type: "coin", col: 9, row: 1, },
        { type: "coin", col: 1, row: 2, },
        { type: "coin", col: 5, row: 2, },
        { type: "coin", col: 9, row: 2, },
        { type: "coin", col: 1, row: 3, },
        { type: "coin", col: 3, row: 3, },
        { type: "coin", col: 4, row: 3, },
        { type: "coin", col: 5, row: 3, },
        { type: "coin", col: 6, row: 3, },
        { type: "coin", col: 7, row: 3, },
        { type: "coin", col: 9, row: 3, },
        { type: "coin", col: 1, row: 4, },
        { type: "coin", col: 2, row: 4, },
        { type: "coin", col: 3, row: 4, },
        { type: "coin", col: 7, row: 4, },
        { type: "coin", col: 8, row: 4, },
        { type: "coin", col: 9, row: 4, },
        { type: "coin", col: 1, row: 5, },
        { type: "coin", col: 3, row: 5, },
        { type: "coin", col: 7, row: 5, },
        { type: "coin", col: 9, row: 5, },
        { type: "coin", col: 1, row: 6, },
        { type: "coin", col: 3, row: 6, },
        { type: "coin", col: 7, row: 6, },
        { type: "coin", col: 9, row: 6, },
        { type: "coin", col: 1, row: 7, },
        { type: "coin", col: 3, row: 7, },
        { type: "coin", col: 7, row: 7, },
        { type: "coin", col: 9, row: 7, },
        { type: "coin", col: 1, row: 8, },
        { type: "coin", col: 3, row: 8, },
        { type: "coin", col: 4, row: 8, },
        { type: "coin", col: 5, row: 8, },
        { type: "coin", col: 6, row: 8, },
        { type: "coin", col: 7, row: 8, },
        { type: "coin", col: 9, row: 8, },
        { type: "coin", col: 1, row: 9, },
        { type: "coin", col: 2, row: 9, },
        { type: "coin", col: 3, row: 9, },
        { type: "coin", col: 7, row: 9, },
        { type: "coin", col: 8, row: 9, },
        { type: "coin", col: 9, row: 9, },
    ],
    GhostBase: { row: 6, col: 5 },
});

AllLevels.set(2, {
    lvlHeight: 13,
    lvlWidth: 13,
    WallMap: [ //          X
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1], //X
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    PacManStartingCoordinates: { row: 1, col: 6 },
    GhostToSpawnList: [
        { row: 11, col: 6, pathfindingStrategy: new AStarPathfindingStrategy(), speedratio: 0.9 },
        { row: 11, col: 6, pathfindingStrategy: new AStarPathfindingStrategy(), speedratio: 0.9 },
    ],
    GhostBase: { row: 13, col: 1 },
    CollictablesToSpawnList: [
        { type: "coin", col: 1, row: 1, },
        { type: "coin", col: 2, row: 1, },
        { type: "coin", col: 3, row: 1, },
        { type: "coin", col: 4, row: 1, },
        { type: "coin", col: 6, row: 1, },
        { type: "coin", col: 8, row: 1, },
        { type: "coin", col: 9, row: 1, },
        { type: "coin", col: 10, row: 1, },
        { type: "coin", col: 11, row: 1, },
        { type: "coin", col: 1, row: 2, },
        { type: "coin", col: 4, row: 2, },
        { type: "coin", col: 6, row: 2, },
        { type: "coin", col: 8, row: 2, },
        { type: "coin", col: 11, row: 2, },
        { type: "coin", col: 1, row: 3, },
        { type: "coin", col: 3, row: 3, },
        { type: "coin", col: 4, row: 3, },
        { type: "coin", col: 5, row: 3, },
        { type: "coin", col: 6, row: 3, },
        { type: "coin", col: 7, row: 3, },
        { type: "coin", col: 8, row: 3, },
        { type: "coin", col: 9, row: 3, },
        { type: "coin", col: 11, row: 3, },
        { type: "coin", col: 1, row: 4, },
        { type: "coin", col: 2, row: 4, },
        { type: "coin", col: 3, row: 4, },
        { type: "coin", col: 9, row: 4, },
        { type: "coin", col: 10, row: 4, },
        { type: "coin", col: 11, row: 4, },
        { type: "coin", col: 1, row: 5, },
        { type: "coin", col: 3, row: 5, },
        { type: "coin", col: 4, row: 5, },
        { type: "coin", col: 5, row: 5, },
        { type: "coin", col: 6, row: 5, },
        { type: "coin", col: 7, row: 5, },
        { type: "coin", col: 8, row: 5, },
        { type: "coin", col: 9, row: 5, },
        { type: "coin", col: 11, row: 5, },
        { type: "coin", col: 1, row: 6, },
        { type: "coin", col: 4, row: 6, },
        { type: "coin", col: 6, row: 6, },
        { type: "coin", col: 8, row: 6, },
        { type: "coin", col: 11, row: 6, },
        { type: "coin", col: 1, row: 7, },
        { type: "coin", col: 3, row: 7, },
        { type: "coin", col: 4, row: 7, },
        { type: "coin", col: 5, row: 7, },
        { type: "coin", col: 6, row: 7, },
        { type: "coin", col: 7, row: 7, },
        { type: "coin", col: 8, row: 7, },
        { type: "coin", col: 9, row: 7, },
        { type: "coin", col: 11, row: 7, },
        { type: "coin", col: 1, row: 8, },
        { type: "coin", col: 2, row: 8, },
        { type: "coin", col: 3, row: 8, },
        { type: "coin", col: 9, row: 8, },
        { type: "coin", col: 10, row: 8, },
        { type: "coin", col: 11, row: 8, },
        { type: "coin", col: 1, row: 9, },
        { type: "coin", col: 3, row: 9, },
        { type: "coin", col: 4, row: 9, },
        { type: "coin", col: 5, row: 9, },
        { type: "coin", col: 6, row: 9, },
        { type: "coin", col: 7, row: 9, },
        { type: "coin", col: 8, row: 9, },
        { type: "coin", col: 9, row: 9, },
        { type: "coin", col: 11, row: 9, },
        { type: "coin", col: 1, row: 10, },
        { type: "coin", col: 4, row: 10, },
        { type: "coin", col: 6, row: 10, },
        { type: "coin", col: 8, row: 10, },
        { type: "coin", col: 11, row: 10, },
        { type: "coin", col: 1, row: 11, },
        { type: "coin", col: 2, row: 11, },
        { type: "coin", col: 3, row: 11, },
        { type: "coin", col: 4, row: 11, },
        { type: "coin", col: 6, row: 11, },
        { type: "coin", col: 8, row: 11, },
        { type: "coin", col: 9, row: 11, },
        { type: "coin", col: 10, row: 11, },
        { type: "coin", col: 11, row: 11, },
    ],
});

// let lvl = AllLevels.get(1);
// let CollictablesToSpawnList = []
// for (let i = 0; i < 13; i++) {
//     for (let j = 0; j < 13; j++) {
//         if (lvl.WallMap[i][j] === 0) {
//             CollictablesToSpawnList.push({ type: "coin", col: j, row: i });
//         }
//     }
// }
// console.log(CollictablesToSpawnList);